USE [master]
GO

/****** Object:  Database [StagingArea]    Script Date: 5/25/2022 9:39:27 AM ******/
CREATE DATABASE [StagingArea]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StagingArea', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\StagingArea.mdf' , SIZE = 21614592KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StagingArea_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\StagingArea_log.ldf' , SIZE = 9228288KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StagingArea].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StagingArea] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StagingArea] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StagingArea] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StagingArea] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StagingArea] SET ARITHABORT OFF 
GO

ALTER DATABASE [StagingArea] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StagingArea] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StagingArea] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StagingArea] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StagingArea] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StagingArea] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StagingArea] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StagingArea] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StagingArea] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StagingArea] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StagingArea] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StagingArea] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StagingArea] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StagingArea] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StagingArea] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StagingArea] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StagingArea] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StagingArea] SET RECOVERY FULL 
GO

ALTER DATABASE [StagingArea] SET  MULTI_USER 
GO

ALTER DATABASE [StagingArea] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StagingArea] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StagingArea] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StagingArea] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StagingArea] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StagingArea] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [StagingArea] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StagingArea] SET  READ_WRITE 
GO

